version: 'build-{build}'
install:
 - git submodule update --init --recursive
test: off
build_script:
 - dotnet restore --configfile ./build/NuGet.config
 - dotnet build -c Release IridiumIon.Analytics/src/IridiumIon.Analytics
 - dotnet publish -c Release IridiumIon.Analytics/src/IridiumIon.Analytics
# Publish
after_build:
 - 7z a -r IridiumIon.Analytics_Standalone-CE.zip %APPVEYOR_BUILD_FOLDER%/IridiumIon.Analytics/src/IridiumIon.Analytics/bin/Release/netcoreapp1.0/publish/*.*

# Artifacts
artifacts:
 - path: IridiumIon.Analytics_Standalone-CE.zip
   name: IridiumIon.Analytics_Standalone_CE_build